// Dental practices data for O'Fallon area
const dentistsData = [
  {
    id: 'spring-valley-dental',
    name: 'Spring Valley Dental Group',
    type: 'General/Family/Cosmetic',
    priceRange: 'Varies by procedure',
    hours: 'Mon-Fri: Standard business hours',
    address: '1234 Spring Valley Dr, O\'Fallon, IL 62269',
    coordinates: [38.5922, -89.9104],
    phone: '(618) 555-0123',
    website: 'https://springvalleydental.com',
    rating: 4.9,
    reviewCount: 0,
    isPremium: true,
    features: [
      'Comprehensive dental care',
      'Family-friendly environment',
      'Modern dental technology'
    ],
    description: 'Spring Valley Dental Group provides comprehensive dental care for the entire family with a focus on personalized treatment plans and patient comfort.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Sedation Options', 'Family-Friendly', 'Modern Technology'],
    priceCategory: 'moderate'
  },
  {
    id: 'innovation-dental',
    name: 'Innovation Dental',
    type: 'General/Cosmetic/Implant Focus',
    priceRange: 'Premium',
    hours: 'Mon-Wed: 8:00 AM - 5:00 PM, Thu: 8:00 AM - 1:00 PM',
    address: '123 Insight Ave, O\'Fallon, IL 62269',
    coordinates: [38.5945, -89.9087],
    phone: '(618) 555-0124',
    website: 'https://innovationdental.com',
    rating: 5.0,
    reviewCount: 1002,
    isPremium: false,
    features: [
      'Implant specialists',
      'IV sedation available',
      'Advanced technology'
    ],
    description: 'Innovation Dental specializes in dental implants and advanced cosmetic procedures using the latest technology.',
    specialties: ['General Dentistry', 'Cosmetic Dentistry', 'Dental Implants'],
    amenities: ['Sedation Options', 'Advanced Technology', 'Implant Specialists'],
    priceCategory: 'premium'
  },
  {
    id: 'shiloh-dental',
    name: 'Shiloh Dental Group',
    type: 'General/Prosthodontics',
    priceRange: 'Premium',
    hours: 'Contact for hours',
    address: '456 Shiloh Rd, Shiloh, IL 62269',
    coordinates: [38.5598, -89.8976],
    phone: '(618) 555-0125',
    website: 'https://shilohdental.com',
    rating: 5.0,
    reviewCount: 263,
    isPremium: false,
    features: [
      'Prosthodontic specialty',
      'Comprehensive dental care',
      'Experienced team'
    ],
    description: 'Shiloh Dental Group offers comprehensive dental care with a specialty in prosthodontics and restorative dentistry.',
    specialties: ['General Dentistry', 'Prosthodontics'],
    amenities: ['Specialty Care', 'Experienced Team'],
    priceCategory: 'premium'
  },
  {
    id: 'bollmeier-dental',
    name: 'Bollmeier Dental',
    type: 'General/Family/Cosmetic/Pediatric',
    priceRange: 'Moderate to Premium',
    hours: 'Mon: 8:30 AM - 5:00 PM, Tue: 8:00 AM - 4:30 PM, Wed: 1:30 PM - 7:00 PM, Thu: 9:00 AM - 5:30 PM',
    address: '789 Main St, O\'Fallon, IL 62269',
    coordinates: [38.5889, -89.9156],
    phone: '(618) 555-0126',
    website: 'https://bollmeierdental.com',
    rating: 4.9,
    reviewCount: 312,
    isPremium: false,
    features: [
      'Comfort dog on staff',
      'Family-friendly environment',
      'Comprehensive care'
    ],
    description: 'Bollmeier Dental provides comprehensive family dental care with a unique comfort dog program for anxious patients.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry', 'Pediatric Dentistry'],
    amenities: ['Pediatric-Friendly', 'Comfort Dog', 'Evening Hours'],
    priceCategory: 'moderate'
  },
  {
    id: 'dream-dentist',
    name: 'Dream Dentist',
    type: 'General/Cosmetic/Sedation',
    priceRange: 'Premium',
    hours: 'Contact for hours',
    address: '321 Dream Ln, O\'Fallon, IL 62269',
    coordinates: [38.5967, -89.9023],
    phone: '(618) 555-0127',
    website: 'https://dreamdentist.com',
    rating: 4.9,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Sedation specialists',
      'Anxiety-friendly practice',
      'Cosmetic focus'
    ],
    description: 'Dream Dentist specializes in sedation dentistry and cosmetic procedures for patients with dental anxiety.',
    specialties: ['General Dentistry', 'Cosmetic Dentistry', 'Sedation Dentistry'],
    amenities: ['Sedation Options', 'Anxiety-Friendly', 'Cosmetic Focus'],
    priceCategory: 'premium'
  },
  {
    id: 'frank-scott-dental',
    name: 'Frank Scott Parkway Dental',
    type: 'General/Cosmetic',
    priceRange: 'Moderate',
    hours: 'Extended hours Thursday',
    address: '654 Frank Scott Pkwy, Shiloh, IL 62269',
    coordinates: [38.5634, -89.8945],
    phone: '(618) 555-0128',
    website: 'https://frankscottdental.com',
    rating: 4.9,
    reviewCount: 14,
    isPremium: false,
    features: [
      'General dentistry',
      'Cosmetic services',
      'Quality care'
    ],
    description: 'Frank Scott Parkway Dental offers quality general and cosmetic dental services with extended Thursday hours.',
    specialties: ['General Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Extended Hours', 'Quality Care'],
    priceCategory: 'moderate'
  },
  {
    id: 'green-mount-family',
    name: 'Green Mount Family Dentistry',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate',
    hours: 'Mon: 8:00 AM - 6:00 PM, Tue: 8:00 AM - 5:00 PM, Wed: 8:00 AM - 6:00 PM, Thu: 8:00 AM - 6:00 PM, Fri: 8:00 AM - 1:00 PM',
    address: '987 Green Mount Rd, O\'Fallon, IL 62269',
    coordinates: [38.5812, -89.9234],
    phone: '(618) 555-0129',
    website: 'https://greenmountdental.com',
    rating: 4.89,
    reviewCount: 9,
    isPremium: false,
    features: [
      'Family dental care',
      'Cosmetic services',
      'Invisalign provider'
    ],
    description: 'Green Mount Family Dentistry provides comprehensive family dental care with cosmetic services and Invisalign treatment.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Invisalign', 'Extended Hours'],
    priceCategory: 'moderate'
  },
  {
    id: 'all-grins-kids',
    name: 'All Grins 4 Kids Pediatric Dentistry',
    type: 'Pediatric',
    priceRange: 'Moderate',
    hours: 'Monday - Thursday: 9:00 AM - 5:00 PM',
    address: '147 Kids Way, O\'Fallon, IL 62269',
    coordinates: [38.5756, -89.9178],
    phone: '(618) 555-0130',
    website: 'https://allgrins4kids.com',
    rating: 4.8,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Pediatric specialists',
      'Special needs care',
      'Child-friendly environment'
    ],
    description: 'All Grins 4 Kids specializes in pediatric dentistry with a focus on special needs children and creating a fun, comfortable environment.',
    specialties: ['Pediatric Dentistry'],
    amenities: ['Pediatric-Friendly', 'Special Needs Care', 'Child-Friendly Environment'],
    priceCategory: 'moderate'
  },
  {
    id: 'azar-orthodontics',
    name: 'Azar Orthodontics',
    type: 'Orthodontic',
    priceRange: 'Premium',
    hours: 'Contact for hours',
    address: '258 Straight St, O\'Fallon, IL 62269',
    coordinates: [38.5834, -89.9067],
    phone: '(618) 555-0131',
    website: 'https://azarortho.com',
    rating: 4.8,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Orthodontic specialists',
      'Braces and aligners',
      'Smile transformation'
    ],
    description: 'Azar Orthodontics specializes in orthodontic treatment including traditional braces and clear aligners for all ages.',
    specialties: ['Orthodontics'],
    amenities: ['Orthodontic Specialists', 'Braces', 'Clear Aligners'],
    priceCategory: 'premium'
  },
  {
    id: 'hometown-dental',
    name: 'Hometown Dental',
    type: 'Family & Cosmetic',
    priceRange: 'Moderate',
    hours: 'Contact for hours',
    address: '369 Hometown Ave, O\'Fallon, IL 62269',
    coordinates: [38.5901, -89.9189],
    phone: '(618) 555-0132',
    website: 'https://hometowndental.com',
    rating: 4.8,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Family dental care',
      'Cosmetic services',
      'Clear treatment plans'
    ],
    description: 'Hometown Dental provides family and cosmetic dental services with clear treatment plans and transparent pricing.',
    specialties: ['Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Clear Treatment Plans'],
    priceCategory: 'moderate'
  },
  {
    id: 'park-place-dental',
    name: 'Park Place Dental Group',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate to Premium',
    hours: 'Extended hours Mon-Thurs',
    address: '741 Park Place Blvd, O\'Fallon, IL 62269',
    coordinates: [38.5723, -89.9298],
    phone: '(618) 555-0133',
    website: 'https://parkplacedental.com',
    rating: 4.8,
    reviewCount: 76,
    isPremium: false,
    features: [
      'Comprehensive dental care',
      'Family-friendly practice',
      'Modern technology'
    ],
    description: 'Park Place Dental Group offers comprehensive dental care for families with modern technology and extended hours.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Extended Hours', 'Modern Technology'],
    priceCategory: 'moderate'
  },
  {
    id: 'ofallon-family-dental',
    name: 'O\'Fallon Family Dental',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate',
    hours: 'Standard business hours',
    address: '852 Family Dr, O\'Fallon, IL 62269',
    coordinates: [38.5867, -89.9045],
    phone: '(618) 555-0134',
    website: 'https://ofallonfamilydental.com',
    rating: 4.7,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Family dental care',
      'Cosmetic services',
      'General dentistry'
    ],
    description: 'O\'Fallon Family Dental provides comprehensive family dental care with cosmetic services in a comfortable environment.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Cosmetic Services'],
    priceCategory: 'moderate'
  },
  {
    id: 'gentle-dental-care',
    name: 'Gentle Dental Care',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate',
    hours: 'Extended hours Mon/Thurs',
    address: '963 Gentle Way, O\'Fallon, IL 62269',
    coordinates: [38.5945, -89.9134],
    phone: '(618) 555-0135',
    website: 'https://gentledentalcare.com',
    rating: 4.7,
    reviewCount: 285,
    isPremium: false,
    features: [
      'Comprehensive dental care',
      'Family-friendly practice',
      'Sedation options'
    ],
    description: 'Gentle Dental Care focuses on providing comfortable dental experiences with sedation options for anxious patients.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Sedation Options', 'Extended Hours'],
    priceCategory: 'moderate'
  },
  {
    id: 'smile-center',
    name: 'Smile Center',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate',
    hours: 'Evening hours by appointment',
    address: '159 Smile St, O\'Fallon, IL 62269',
    coordinates: [38.5778, -89.9067],
    phone: '(618) 555-0136',
    website: 'https://smilecenter.com',
    rating: 4.7,
    reviewCount: 0,
    isPremium: false,
    features: [
      'Family dental care',
      'Cosmetic services',
      'Personalized treatment'
    ],
    description: 'Smile Center provides personalized dental care for families with cosmetic services and flexible evening appointments.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Family-Friendly', 'Evening Hours', 'Personalized Care'],
    priceCategory: 'moderate'
  },
  {
    id: 'comfort-dental',
    name: 'Comfort Dental',
    type: 'General/Family/Cosmetic',
    priceRange: 'Moderate to Premium',
    hours: 'Contact for hours',
    address: '357 Comfort Ln, O\'Fallon, IL 62269',
    coordinates: [38.5812, -89.9123],
    phone: '(618) 555-0137',
    website: 'https://comfortdental.com',
    rating: 4.7,
    reviewCount: 50,
    isPremium: false,
    features: [
      'Gentle dental care',
      'Oral and IV sedation',
      'Family-friendly practice'
    ],
    description: 'Comfort Dental specializes in gentle dental care with comprehensive sedation options for patient comfort.',
    specialties: ['General Dentistry', 'Family Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Sedation Options', 'Family-Friendly', 'Gentle Care'],
    priceCategory: 'moderate'
  },
  {
    id: 'modern-dental',
    name: 'Modern Dental',
    type: 'General/Cosmetic',
    priceRange: 'Moderate to Premium',
    hours: 'Standard business hours',
    address: '753 Modern Way, O\'Fallon, IL 62269',
    coordinates: [38.5689, -89.9201],
    phone: '(618) 555-0138',
    website: 'https://moderndental.com',
    rating: 4.7,
    reviewCount: 0,
    isPremium: false,
    features: [
      'General dentistry',
      'Cosmetic services',
      'Nitrous oxide available'
    ],
    description: 'Modern Dental offers general and cosmetic dental services with modern technology and nitrous oxide for patient comfort.',
    specialties: ['General Dentistry', 'Cosmetic Dentistry'],
    amenities: ['Modern Technology', 'Nitrous Oxide'],
    priceCategory: 'moderate'
  },
  {
    id: 'affordable-dentures',
    name: 'Affordable Dentures & Implants',
    type: 'General/Cosmetic/Multi-Specialty',
    priceRange: 'Budget to Moderate',
    hours: 'Extended hours available',
    address: '951 Budget Blvd, O\'Fallon, IL 62269',
    coordinates: [38.5634, -89.9089],
    phone: '(618) 555-0139',
    website: 'https://affordabledentures.com',
    rating: 4.2,
    reviewCount: 691,
    isPremium: false,
    features: [
      'Denture specialists',
      'Emergency care',
      'Multiple services'
    ],
    description: 'Affordable Dentures & Implants specializes in dentures, implants, and emergency dental care with budget-friendly options.',
    specialties: ['General Dentistry', 'Dentures', 'Dental Implants'],
    amenities: ['Budget-Friendly', 'Emergency Care', 'Extended Hours'],
    priceCategory: 'budget'
  }
];

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = dentistsData;
}

