// Enhanced O'Fallon area dental practices data - Using competitive intelligence insights
const dentistsData = [
  {
    id: "springvalley",
    name: "Spring Valley Dental Group",
    type: "General/Family/Cosmetic",
    price: "Moderate to Premium",
    hours: "Mon-Fri: Standard business hours",
    features: [
      "Comprehensive family dental care",
      "Personalized treatment plans", 
      "Modern dental technology"
    ],
    amenities: [
      "Sedation options available",
      "Accepts most insurance plans",
      "In-house payment plans"
    ],
    rating: 4.9,
    reviews: "N/A",
    bbbRating: "A+",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://springvalleydentalgroup.com/",
    logo: "images/logos/springvalley.png",
    isPremium: true,
    acceptsCareCredit: true,
    hasInHousePlan: true,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: false,
    specialCredentials: "Family-focused comprehensive care specialists",
    marketPosition: "Premier family dental practice with personalized attention"
  },
  {
    id: "innovationdental",
    name: "Innovation Dental",
    type: "General/Cosmetic/Implant Specialists",
    price: "Premium",
    hours: "Mon-Wed: 8:00 AM - 5:00 PM, Thu: 8:00 AM - 1:00 PM",
    features: [
      "Advanced implant specialists",
      "Same-day dental crowns",
      "IV sedation available"
    ],
    amenities: [
      "Fellowship-trained implant specialist",
      "Latest dental technology",
      "Comprehensive financing options"
    ],
    rating: 5.0,
    reviews: 1002,
    bbbRating: "A+",
    address: "717 Insight Avenue, Suite 200, O'Fallon, IL 62269",
    phone: "(618) 277-6550",
    website: "https://www.innovationdentalgroup.com/",
    logo: "images/logos/innovationl.jpg",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: true,
    offersSedation: true,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Fellowship in International Congress of Oral Implantologists",
    marketPosition: "Technology-forward practice with advanced implant expertise"
  },
  {
    id: "shilohdentalgroup",
    name: "Shiloh Dental Group",
    type: "General/Prosthodontics Specialists",
    price: "Premium",
    hours: "Contact for hours",
    features: [
      "Prosthodontic specialty care",
      "Complex restorative procedures",
      "Experienced specialist team"
    ],
    amenities: [
      "Advanced restorative techniques",
      "Patient-centered approach",
      "Comprehensive financing options"
    ],
    rating: 5.0,
    reviews: 263,
    bbbRating: "A+",
    address: "Shiloh, IL 62269",
    phone: "Contact via website",
    website: "https://shilohdentalgroup.com/",
    logo: "images/logos/shilohdental.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Prosthodontic specialists",
    marketPosition: "Advanced restorative and reconstructive dental experts"
  },
  {
    id: "bollmeierdental",
    name: "Bollmeier Dental",
    type: "General/Family/Cosmetic/Pediatric",
    price: "Moderate to Premium",
    hours: "Mon: 8:30 AM - 5:00 PM, Tue: 8:00 AM - 4:30 PM, Wed: 1:30 PM - 7:00 PM, Thu: 9:00 AM - 5:30 PM",
    features: [
      "Comfort dog therapy on staff",
      "Massage chairs in treatment rooms",
      "Family-friendly anxiety management"
    ],
    amenities: [
      "Nitrous oxide sedation",
      "Senior discounts available",
      "Extended evening hours"
    ],
    rating: 4.9,
    reviews: 312,
    bbbRating: "A+",
    address: "2010 W US Highway 50, O'Fallon, IL 62269",
    phone: "(618) 622-8888",
    website: "http://bollmeierdental.com/",
    logo: "images/logos/bollmeier.jpg",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: true,
    specialCredentials: "Unique comfort dog therapy program",
    marketPosition: "Anxiety-focused family practice with premium comfort amenities"
  },
  {
    id: "parkplacedental",
    name: "Park Place Dental Group",
    type: "General/Family/Cosmetic",
    price: "Moderate to Premium",
    hours: "Extended hours Mon-Thurs",
    features: [
      "Comprehensive family services",
      "Flexible scheduling options",
      "Modern treatment technology"
    ],
    amenities: [
      "Multiple sedation options",
      "In-house payment plans",
      "Most insurance accepted"
    ],
    rating: 4.8,
    reviews: 76,
    bbbRating: "A+",
    address: "Shiloh, IL 62269",
    phone: "Contact via website",
    website: "https://parkplacedentalgroup.com/",
    logo: "images/logos/parkplace.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: true,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: true,
    specialCredentials: "Extended hour specialists",
    marketPosition: "Convenient, family-focused practice with flexible scheduling"
  },
  {
    id: "greenmountfamily",
    name: "Green Mount Family Dentistry",
    type: "General/Family/Cosmetic",
    price: "Moderate",
    hours: "Mon: 8:00 AM - 6:00 PM, Tue: 8:00 AM - 5:00 PM, Wed: 8:00 AM - 6:00 PM, Thu: 8:00 AM - 6:00 PM, Fri: 8:00 AM - 1:00 PM",
    features: [
      "Invisalign provider",
      "Comprehensive cosmetic services",
      "Family dental care specialists"
    ],
    amenities: [
      "Modern facility design",
      "Extended evening hours",
      "Flexible financing options"
    ],
    rating: 4.89,
    reviews: 9,
    bbbRating: "A+",
    address: "1490 North Greenmount Road, Suite A, O'Fallon, IL 62269",
    phone: "(618) 622-9720",
    website: "https://greenmountfamilydentistry.com/",
    logo: "images/logos/greenmountfamily.svg",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: true,
    specialCredentials: "Certified Invisalign provider",
    marketPosition: "Cosmetic-focused family practice with evening convenience"
  },
  {
    id: "lakepointedental",
    name: "Lake Pointe Dental Group",
    type: "General/Family/Cosmetic",
    price: "Moderate",
    hours: "Extended hours Mon/Thurs",
    features: [
      "Emergency dental care",
      "Comprehensive family services",
      "Same-day appointments available"
    ],
    amenities: [
      "Modern facility amenities",
      "Multiple financing options",
      "Convenient evening hours"
    ],
    rating: 4.7,
    reviews: 285,
    bbbRating: "A+",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://lakepointedentalgroup.com/",
    logo: "images/logos/lakepointe.webp",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: false,
    hasEveningHours: true,
    specialCredentials: "Emergency care specialists",
    marketPosition: "Reliable family practice with strong emergency availability"
  },
  {
    id: "softtouchdentistry",
    name: "Soft Touch Dentistry",
    type: "General/Family/Cosmetic",
    price: "Moderate to Premium",
    hours: "Contact for hours",
    features: [
      "Gentle dental care philosophy",
      "Oral and IV sedation specialists",
      "Anxiety-focused treatment approach"
    ],
    amenities: [
      "Spa-like comfortable environment",
      "Comprehensive pediatric services",
      "Flexible financing options"
    ],
    rating: 4.7,
    reviews: 50,
    bbbRating: "N/A",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://softtouchdentistry.com/",
    logo: "images/logos/softtouch.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: false,
    specialCredentials: "Anxiety management specialists",
    marketPosition: "Premier gentle care practice for anxious patients"
  },
  {
    id: "aspendental",
    name: "Aspen Dental",
    type: "General/Cosmetic/Multi-Specialty",
    price: "Budget to Moderate",
    hours: "Extended hours available",
    features: [
      "Denture and restoration specialists",
      "Transparent pricing model",
      "Emergency dental care"
    ],
    amenities: [
      "Peace of Mind Promise® warranty",
      "Convenient scheduling system",
      "Multiple financing options"
    ],
    rating: 4.2,
    reviews: 691,
    bbbRating: "N/A",
    address: "1707 West Highway 50, O'Fallon, IL 62269",
    phone: "(618) 206-5488",
    website: "https://www.aspendental.com/dentist/il/o-fallon/",
    logo: "images/logos/aspen.svg",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: false,
    hasEveningHours: true,
    specialCredentials: "National chain with standardized care protocols",
    marketPosition: "Budget-conscious option with transparent pricing and convenience"
  },
  {
    id: "allgrins4kids",
    name: "All Grins 4 Kids Pediatric Dentistry",
    type: "Pediatric Specialists",
    price: "Moderate",
    hours: "Monday - Thursday: 9:00 AM - 5:00 PM",
    features: [
      "Board-certified pediatric dentists",
      "Special needs patient expertise",
      "Child-focused environment design"
    ],
    amenities: [
      "Nitrous oxide sedation",
      "Digital diagnostic technology",
      "Family referral rewards program"
    ],
    rating: 4.8,
    reviews: "N/A",
    bbbRating: "N/A",
    address: "317 Tamarack Lane, Shiloh, IL 62269",
    phone: "(618) 628-4400",
    website: "https://www.allgrins4kids.com/",
    logo: "images/logos/allgrins4kids.svg",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: false,
    specialCredentials: "Board-certified pediatric dental specialists",
    marketPosition: "Dedicated pediatric practice with special needs expertise"
  },
  {
    id: "dreamdentist",
    name: "Dream Dentist",
    type: "General/Cosmetic/Sedation Specialists",
    price: "Premium",
    hours: "Monday – Thursday, 8:00 AM – 4:00 PM",
    features: [
      "Licensed IV sedation specialists",
      "Award-winning cosmetic dentistry",
      "Anxiety-free dental experience"
    ],
    amenities: [
      "Spa-like treatment environment",
      "Oral and IV sedation options",
      "Mercury-free treatment philosophy"
    ],
    rating: 4.9,
    reviews: "N/A",
    bbbRating: "A+",
    address: "1646 W Highway 50, O'Fallon, IL 62269",
    phone: "(618) 726-2699",
    website: "https://www.dreamdentist.com/",
    logo: "images/logos/dreamdentist.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Licensed IV sedation specialist with cosmetic expertise",
    marketPosition: "Luxury cosmetic and sedation dentistry specialists"
  },
  {
    id: "hometowndental",
    name: "Hometown Dental",
    type: "Family & Cosmetic",
    price: "Moderate",
    hours: "Contact for hours",
    features: [
      "Transparent pricing philosophy",
      "Clear treatment communication",
      "Family-focused dental care"
    ],
    amenities: [
      "No-pressure treatment approach",
      "Honest pricing discussions",
      "Flexible financing options"
    ],
    rating: 4.8,
    reviews: "N/A",
    bbbRating: "N/A",
    address: "904 Talon Drive, O'Fallon, IL 62269",
    phone: "618-726-2280",
    website: "https://www.home-towndental.com/",
    logo: "images/logos/hometown.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Transparent pricing specialists",
    marketPosition: "Honest, small-town approach with transparent pricing"
  },
  {
    id: "markmedder",
    name: "Mark Medder DMD",
    type: "General/Family/Cosmetic",
    price: "Moderate",
    hours: "Evening hours by appointment",
    features: [
      "Personalized individual attention",
      "Flexible scheduling accommodations",
      "Comprehensive family care"
    ],
    amenities: [
      "Nitrous oxide comfort options",
      "Personal relationship focus",
      "Accommodating appointment times"
    ],
    rating: 4.7,
    reviews: "N/A",
    bbbRating: "A+",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://markmedder.com/",
    logo: "images/logos/markmedder.webp",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: true,
    isPediatricFriendly: false,
    hasEveningHours: true,
    specialCredentials: "Personalized care specialist",
    marketPosition: "Individual-focused practice with personal attention and flexibility"
  },
  {
    id: "cambridgedental",
    name: "Cambridge Dental Care",
    type: "General/Family/Cosmetic/Periodontal",
    price: "Moderate",
    hours: "Mon-Wed: 8:00 AM - 5:00 PM, Thu: 8:00 AM - 3:00 PM, Fri: 8:00 AM - 2:00 PM",
    features: [
      "Laser Assisted Periodontal Therapy (LAPT)",
      "Advanced periodontal treatments",
      "Comprehensive family services"
    ],
    amenities: [
      "Latest dental technology",
      "Laser dentistry capabilities",
      "Insurance coordination services"
    ],
    rating: 4.9,
    reviews: 943,
    bbbRating: "A+",
    address: "1490 North Greenmount Road, Suite B, O'Fallon, IL 62269",
    phone: "(618) 632-1603",
    website: "https://cambridgefamilydentistry.com/",
    logo: "images/logos/cambridge.webp",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Laser dentistry and advanced periodontal specialists",
    marketPosition: "Technology-advanced family practice with exceptional community trust"
  },
  {
    id: "frankscottdental",
    name: "Frank Scott Parkway Dental",
    type: "General/Cosmetic",
    price: "Moderate",
    hours: "Extended hours Thursday",
    features: [
      "Quality general dentistry",
      "Cosmetic enhancement services",
      "Thursday evening availability"
    ],
    amenities: [
      "Modern dental facility",
      "Financing accommodations",
      "Evening appointment options"
    ],
    rating: 4.9,
    reviews: 14,
    bbbRating: "Not Accredited",
    address: "Swansea, IL",
    phone: "Contact via website",
    website: "https://frankscottdental.com/",
    logo: "images/logos/frankscottparkway.png",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: true,
    specialCredentials: "Swansea area specialists",
    marketPosition: "Reliable general and cosmetic care for greater O'Fallon area"
  },
  {
    id: "azarorthodontics",
    name: "Azar Orthodontics",
    type: "Orthodontic Specialists",
    price: "Premium",
    hours: "Contact for hours",
    features: [
      "Board-certified orthodontists",
      "Advanced aligner therapy",
      "Comprehensive smile transformation"
    ],
    amenities: [
      "Modern orthodontic technology",
      "Flexible financing plans",
      "Complimentary consultations"
    ],
    rating: 4.8,
    reviews: "N/A",
    bbbRating: "A+",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://azarorthodontics.com/",
    logo: "images/logos/azar.png",
    isPremium: false,
    acceptsCareCredit: false,
    hasInHousePlan: false,
    offersSedation: false,
    isPediatricFriendly: false,
    hasEveningHours: false,
    specialCredentials: "Board-certified orthodontic specialists",
    marketPosition: "Specialized orthodontic expertise for comprehensive smile transformation"
  },
  {
    id: "dentalstudio",
    name: "The Dental Studio",
    type: "General/Cosmetic",
    price: "Moderate to Premium",
    hours: "Standard business hours",
    features: [
      "Comprehensive general dentistry",
      "Advanced cosmetic procedures",
      "Nitrous oxide comfort care"
    ],
    amenities: [
      "In-house payment plan options",
      "Family-friendly environment",
      "Modern studio design"
    ],
    rating: 4.7,
    reviews: "N/A",
    bbbRating: "A+ (as Bowman)",
    address: "O'Fallon, IL 62269",
    phone: "Contact via website",
    website: "https://thedentalstudio.com/",
    logo: "images/logos/dentalstudio.webp",
    isPremium: false,
    acceptsCareCredit: true,
    hasInHousePlan: true,
    offersSedation: true,
    isPediatricFriendly: true,
    hasEveningHours: false,
    specialCredentials: "Modern dental studio concept",
    marketPosition: "Contemporary dental studio with comprehensive family services"
  }
];
